feat: add kubeconfig-file ✨

diff --git a/action.yml b/action.yml
--- a/action.yml
+++ b/action.yml
@@ -29,8 +29,11 @@ inputs:
     default: v3.9.4
     required: false
   kubeconfig:
-    description: 'A JSON/YAML encoded string e.g. {"key": "value"}'
-    required: true
+    description: 'A JSON/YAML encoded string e.g. {"key": "value"}. Mutually exclusive with `kubeconfig-file`'
+    required: false
+  kubeconfig-file:
+    description: Path to kubeconfig file. Mutually exclusive with `kubeconfig`
+    required: false
   namespace:
     default: default
     required: false
@@ -60,6 +63,18 @@ inputs:
 runs:
   using: composite
   steps:
+    - if: inputs.kubeconfig == '' && inputs.kubeconfig-file == ''
+      name: Error - no kubeconfig provided
+      shell: bash
+      run: |
+        echo "Error: You must provide either `kubeconfig` or `kubeconfig-file`"
+        exit 1
+    - if: inputs.kubeconfig != '' && inputs.kubeconfig-file != ''
+      name: Error - both kubeconfig and kubeconfig-file provided
+      shell: bash
+      run: |
+        echo "Error: You must provide either `kubeconfig` or `kubeconfig-file` but not both"
+        exit 1
     - env:
         DESIRED_VERSION: ${{ inputs.helm-version }}
       name: Install Helm ${{ inputs.helm-version }}
@@ -82,6 +97,7 @@ runs:
         chmod 600 ${{ github.run_id }}
       shell: bash
     - name: Prepare KUBECONFIG
+      if: inputs.kubeconfig != '' && inputs.kubeconfig-file != ''
       run: |
         cat << 'EOF' > /tmp/kubeconfig
         ${{ inputs.kubeconfig }}
@@ -91,7 +107,7 @@ runs:
     - name: Deploy with Helm
       run: |
         helm ${{ inputs.action }} ${{ inputs.release-name }} ${{ inputs.chart-dir }} \
-          --kubeconfig /tmp/kubeconfig \
+          --kubeconfig ${{ inputs.kubeconfig-file || '/tmp/kubeconfig' }} \
           --namespace ${{ inputs.namespace }} \
           $([[ "${{ inputs.create-namespace }}" == "1" ]] && echo '--create-namespace') \
           $([[ "${{ inputs.atomic }}" == "1" ]] && echo '--atomic') \
